#!/usr/bin/env python3
"""Generate `docs/drop-in-parity.md`: the evidence behind the drop-in claim (WP-19).

Three questions decide whether "drop-in replacement" is a fair description, and
this report answers each with a number rather than an adjective:

  1. On real third-party code, do the two tools report the same issues?
     (`scripts/diff_corpus.py --json`)
  2. Across the command-line surface, do they agree on stdout, stderr **and the
     exit code**? (`scripts/cli_matrix.py`)
  3. How much of the tool does that evidence actually exercise — how many of the
     75 test ids does the corpus trigger, and which are never reached?

Question 3 is the one it is tempting to skip. Parity over code that never wakes
a plugin proves very little, so the report names the ids the corpus misses
instead of quietly averaging them away.

    scripts/parity_report.py --parity target/parity/full.json [target/parity/frontier.json]
                             [--out docs/drop-in-parity.md]
"""

import argparse
import json
import re
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import corpus  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RS_BANDIT = Path(os.environ.get("RS_BANDIT", ROOT / "target" / "release" / "bandit"))


def loaded_tests():
    """The (id, name) pairs the binary itself reports as loaded — asking the
    tool beats re-deriving the list from the source and drifting from it."""
    out = subprocess.run([str(RS_BANDIT), "--help"], capture_output=True, text=True).stdout
    tail = out.split("The following tests were discovered and loaded:", 1)[-1]
    return dict(re.findall(r"(B\d{3})\t(\S+)", tail))


def examples_test_ids():
    """Test ids `examples/` triggers — where the corpus misses an id, this says
    whether parity for it is already proven by the golden corpus."""
    out = subprocess.run(
        [str(RS_BANDIT), "-r", str(ROOT / "examples"), "-f", "json", "-q"],
        capture_output=True, text=True, env={**os.environ, "BANDITRS_PYTHON_COMPAT": "3.11"},
    ).stdout
    try:
        return {i["test_id"] for i in json.loads(out)["results"]}
    except (json.JSONDecodeError, KeyError):
        return set()


def cli_matrix_summary():
    cases = [
        l.split("\t")[0]
        for l in (ROOT / "tests/cli_matrix/cases.tsv").read_text().splitlines()
        if l.strip() and not l.startswith("#")
    ]
    expected = sorted(p.stem for p in (ROOT / "tests/cli_matrix/out").glob("*.expected"))
    return len(cases), expected


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "--parity",
        required=True,
        nargs="+",
        help="one or more JSON files written by diff_corpus.py --json",
    )
    ap.add_argument("--out", default=str(ROOT / "docs" / "drop-in-parity.md"))
    args = ap.parse_args()

    table = [row for f in args.parity for row in json.loads(Path(f).read_text())]
    parity = [e for e in table if e["tier"] != "frontier"]
    frontier = [e for e in table if e["tier"] == "frontier"]

    tests = loaded_tests()
    hit = sorted({i for e in parity for i in e["test_ids"]})
    missed = sorted(set(tests) - set(hit))
    from_examples = examples_test_ids()
    n_cases, expected_cases = cli_matrix_summary()

    files = sum(e["py_files"] for e in parity)
    lines = sum(e["py_lines"] for e in parity)
    issues = sum(e["issues_python"] or 0 for e in parity)
    identical = [e for e in parity if e["identical"]]
    py_secs = sum(e["seconds_python"] for e in parity)
    rs_secs = sum(e["seconds_rust"] for e in parity)

    d = []
    w = d.append
    w("# Is BanditRS a drop-in replacement? The evidence\n")
    w("Generated by `scripts/parity_report.py`. Every number here comes from running both tools;")
    w("nothing is asserted that a command in this repository cannot reproduce.\n")
    w("## Summary\n")
    w("| Question | Answer |")
    w("|---|---|")
    w(f"| Same issues on real third-party code? | **{len(identical)}/{len(parity)} packages identical** "
      f"— {files:,} files, {lines:,} lines, {issues:,} issues |")
    w(f"| Same stdout, stderr **and exit code** across the CLI? | **{n_cases - len(expected_cases)}/{n_cases} "
      f"invocations identical**, {len(expected_cases)} documented divergence(s) |")
    w(f"| How much of the tool does that exercise? | **{len(hit)}/{len(tests)} test ids** triggered by the "
      f"corpus; the rest are covered by `examples/` (see §3) |")
    w(f"| How much faster? | **{py_secs / rs_secs:.1f}×** over the whole corpus "
      f"({py_secs:.1f} s → {rs_secs:.1f} s) |")
    w("")

    w("## 1. Real third-party code, package by package\n")
    w("Both tools run as `bandit -r <package> -f json -q`. Identical means: the same issues, in the same")
    w("order, with the same file, line, column range, severity, confidence and message; the same `errors[]`;")
    w("and the same `metrics` block, which also proves both discovered the same files with the same line")
    w("counts.\n")
    w("| package | files | lines | issues | errors | verdict | python (s) | rust (s) | speed-up |")
    w("|---|---:|---:|---:|---:|---|---:|---:|---:|")
    for e in sorted(parity, key=lambda x: -x["py_lines"]):
        verdict = "identical" if e["identical"] else "**DIVERGES**"
        speed = e["seconds_python"] / e["seconds_rust"] if e["seconds_rust"] else 0
        w(f"| `{e['name']} {e['version']}` | {e['py_files']:,} | {e['py_lines']:,} | "
          f"{e['issues_python']:,} | {e['errors_python']} | {verdict} | "
          f"{e['seconds_python']:.2f} | {e['seconds_rust']:.2f} | {speed:.1f}× |")
    w(f"| **total** | **{files:,}** | **{lines:,}** | **{issues:,}** | | "
      f"**{len(identical)}/{len(parity)}** | **{py_secs:.1f}** | **{rs_secs:.1f}** | "
      f"**{py_secs / rs_secs:.1f}×** |")
    w("")
    for e in parity:
        if not e["identical"]:
            w(f"Divergence in `{e['name']}`:\n")
            for line in e["diffs"]:
                w(f"    {line}")
            w("")

    w("## 2. The command-line surface\n")
    w(f"`scripts/cli_matrix.py` runs {n_cases} invocations through both tools and compares stdout, stderr and")
    w("the exit code. It covers the severity and confidence thresholds, test selection and skipping, profiles")
    w("and config files, all nine formatters, `--msg-template`, `-o`, context lines, aggregation, `-q`/`-v`/`-d`,")
    w("`--exit-zero`, `--ignore-nosec`, target discovery (recursive or not, excludes, globs, symlinks, missing")
    w("paths, empty directories, non-UTF-8 and unparsable files), `.bandit` handling, every usage error that")
    w("exits 2, baselines, and the `bandit-baseline` / `bandit-config-generator` binaries.\n")
    if expected_cases:
        w(f"Result: **{n_cases - len(expected_cases)}/{n_cases} identical**. The "
          f"{len(expected_cases)} exception(s) are documented in `DEVIATIONS.md`:\n")
        for cid in expected_cases:
            marker = (ROOT / "tests/cli_matrix/out" / f"{cid}.expected").read_text().splitlines()[0]
            w(f"- `{cid}` — {marker}")
    else:
        w(f"Result: **{n_cases}/{n_cases} identical**.")
    w("")
    w("`cargo test --test cli_matrix` replays the recorded reference surface with no Python installed, so a")
    w("regression in any of these is caught by the ordinary test run.\n")

    w("## 3. What the evidence actually exercises\n")
    w(f"The corpus triggers **{len(hit)} of the {len(tests)} loaded test ids**. Parity on code that never wakes")
    w("a plugin would prove very little, so here are the ones it never reaches, and where each is covered")
    w("instead:\n")
    if missed:
        w("| test id | name | covered by `examples/`? |")
        w("|---|---|---|")
        for tid in missed:
            covered = "yes — golden corpus" if tid in from_examples else "**no — blind spot**"
            w(f"| {tid} | {tests[tid]} | {covered} |")
        blind = [t for t in missed if t not in from_examples]
        w("")
        w(f"{len(missed)} id(s) are not reached by the corpus; {len(missed) - len(blind)} of them are covered by")
        w("the `examples/` golden corpus, which is compared against the same reference. That leaves")
        w(f"**{len(blind)} genuinely unexercised**"
          + (f": {', '.join(blind)}." if blind else "."))
    else:
        w("None — the corpus triggers every loaded test id.")
    w("")
    w("Triggered by the corpus: " + ", ".join(hit) + ".\n")

    if frontier:
        w("## 4. The parser target, measured\n")
        w("BanditRS parses with `ruff_python_parser`, whose target version is set by")
        w("`BANDITRS_PYTHON_COMPAT`; the reference parses with the host interpreter's `ast`. This is worth")
        w("being precise about, because it is easy to mistake for a parity gap.\n")
        w("**With the target aligned to the reference (`BANDITRS_PYTHON_COMPAT=3.11`), there is no gap at")
        w("all** — including on packages that require Python 3.12. The `frontier` tier is made of exactly")
        w("those packages, and with the target aligned both tools produce identical reports, `errors[]`")
        w("included: BanditRS refuses the same files, for the same reason.\n")
        w("The numbers below are the *other* regime — BanditRS left on its default (latest) target against a")
        w("3.11 reference — which is what quantifies the difference (DEVIATIONS.md #16):\n")
        w("| package | files | errors (python) | errors (rust) | issues (python) | issues (rust) |")
        w("|---|---:|---:|---:|---:|---:|")
        for e in frontier:
            w(f"| `{e['name']} {e['version']}` | {e['py_files']:,} | {e['errors_python']} | "
              f"{e['errors_rust']} | {e['issues_python']:,} | {e['issues_rust']:,} |")
        w("")
        w("Where the reference records a syntax error and analyses nothing, BanditRS analyses the file, so it")
        w("reports *more*. The remaining difference is the 3.12 f-string constant positions (DEVIATIONS.md")
        w("#7), which move issues found inside an f-string. Comparing against a reference means matching its")
        w("interpreter version; every harness in this repository sets the target accordingly, and every")
        w("package in the parity tiers is additionally pinned to a release CPython 3.11 parses in full")
        w("(`scripts/corpus.py verify --parse`).\n")

    # The commands must name the tiers this very report was built from, not a
    # plausible-looking default: a reproduction block that reproduces something
    # else is worse than none, since it looks checkable.
    order = ["smoke", "standard", "full"]
    widest = max((e["tier"] for e in parity), key=order.index, default="standard")
    parity_json = f"target/parity/{widest}.json"

    w("## Reproducing\n")
    w("```")
    w("cargo build --release")
    w(f"scripts/corpus.py fetch  --tier {widest}{' ' * (8 - len(widest))}      # pinned by sha256")
    w("scripts/corpus.py verify --parse              # precondition: all of it parses under 3.11")
    w(f"scripts/diff_corpus.py   --tier {widest} --json {parity_json}")
    if frontier:
        w(f"scripts/diff_corpus.py   --tier frontier --rs-compat latest --json target/parity/frontier.json")
    w("scripts/cli_matrix.py    diff")
    w(f"scripts/parity_report.py --parity {parity_json}"
      + (" target/parity/frontier.json" if frontier else ""))
    w("```")

    dest = Path(args.out)
    dest.write_text("\n".join(d) + "\n")
    print(f"written: {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
